const css_default_value = {
    alignContent: "normal",
    alignItems: "normal",
    alignSelf: "auto",
    alignmentBaseline: "auto",
    all: "",
    animation: "none 0s ease 0s 1 normal none running",
    animationDelay: "0s",
    animationDirection: "normal",
    animationDuration: "0s",
    animationFillMode: "none",
    animationIterationCount: "1",
    animationName: "none",
    animationPlayState: "running",
    animationTimingFunction: "ease",
    backdropFilter: "none",
    backfaceVisibility: "visible",
    background: "rgba(0, 0, 0, 0) none repeat scroll 0% 0% / auto padding-box border-box",
    backgroundAttachment: "scroll",
    backgroundBlendMode: "normal",
    backgroundClip: "border-box",
    backgroundColor: "rgba(0, 0, 0, 0)",
    backgroundImage: "none",
    backgroundOrigin: "padding-box",
    backgroundPosition: "0% 0%",
    backgroundPositionX: "0%",
    backgroundPositionY: "0%",
    backgroundRepeat: "repeat",
    backgroundRepeatX: "",
    backgroundRepeatY: "",
    backgroundSize: "auto",
    baselineShift: "0px",
    blockSize: "900px",
    border: "0px none rgb(0, 0, 0)",
    borderBlockEnd: "0px none rgb(0, 0, 0)",
    borderBlockEndColor: "rgb(0, 0, 0)",
    borderBlockEndStyle: "none",
    borderBlockEndWidth: "0px",
    borderBlockStart: "0px none rgb(0, 0, 0)",
    borderBlockStartColor: "rgb(0, 0, 0)",
    borderBlockStartStyle: "none",
    borderBlockStartWidth: "0px",
    borderBottom: "0px none rgb(0, 0, 0)",
    borderBottomColor: "rgb(0, 0, 0)",
    borderBottomLeftRadius: "0px",
    borderBottomRightRadius: "0px",
    borderBottomStyle: "none",
    borderBottomWidth: "0px",
    borderCollapse: "separate",
    borderColor: "rgb(0, 0, 0)",
    borderImage: "none",
    borderImageOutset: "0",
    borderImageRepeat: "stretch",
    borderImageSlice: "100%",
    borderImageSource: "none",
    borderImageWidth: "1",
    borderInlineEnd: "0px none rgb(0, 0, 0)",
    borderInlineEndColor: "rgb(0, 0, 0)",
    borderInlineEndStyle: "none",
    borderInlineEndWidth: "0px",
    borderInlineStart: "0px none rgb(0, 0, 0)",
    borderInlineStartColor: "rgb(0, 0, 0)",
    borderInlineStartStyle: "none",
    borderInlineStartWidth: "0px",
    borderLeft: "0px none rgb(0, 0, 0)",
    borderLeftColor: "rgb(0, 0, 0)",
    borderLeftStyle: "none",
    borderLeftWidth: "0px",
    borderRadius: "0px",
    borderRight: "0px none rgb(0, 0, 0)",
    borderRightColor: "rgb(0, 0, 0)",
    borderRightStyle: "none",
    borderRightWidth: "0px",
    borderSpacing: "0px 0px",
    borderStyle: "none",
    borderTop: "0px none rgb(0, 0, 0)",
    borderTopColor: "rgb(0, 0, 0)",
    borderTopLeftRadius: "0px",
    borderTopRightRadius: "0px",
    borderTopStyle: "none",
    borderTopWidth: "0px",
    borderWidth: "0px",
    bottom: "auto",
    boxShadow: "none",
    boxSizing: "content-box",
    breakAfter: "auto",
    breakBefore: "auto",
    breakInside: "auto",
    bufferedRendering: "auto",
    captionSide: "top",
    caretColor: "rgb(0, 0, 0)",
    clear: "none",
    clip: "auto",
    clipPath: "none",
    clipRule: "nonzero",
    color: "rgb(0, 0, 0)",
    colorInterpolation: "srgb",
    colorInterpolationFilters: "linearrgb",
    colorRendering: "auto",
    colorScheme: "normal",
    columnCount: "auto",
    columnFill: "balance",
    columnGap: "normal",
    columnRule: "0px none rgb(0, 0, 0)",
    columnRuleColor: "rgb(0, 0, 0)",
    columnRuleStyle: "none",
    columnRuleWidth: "0px",
    columnSpan: "none",
    columnWidth: "auto",
    columns: "auto auto",
    contain: "none",
    containIntrinsicSize: "auto",
    content: "normal",
    counterIncrement: "none",
    counterReset: "none",
    cssFloat: "none",
    cssText: "animation-delay: 0s; animation-direction: normal; animation-duration: 0s; animation-fill-mode: none; animation-iteration-count: 1; animation-name: none; animation-play-state: running; animation-timing-function: ease; background-attachment: scroll; background-blend-mode: normal; background-clip: border-box; background-color: rgba(0, 0, 0, 0); background-image: none; background-origin: padding-box; background-position: 0% 0%; background-repeat: repeat; background-size: auto; border-bottom-color: rgb(0, 0, 0); border-bottom-left-radius: 0px; border-bottom-right-radius: 0px; border-bottom-style: none; border-bottom-width: 0px; border-collapse: separate; border-image-outset: 0; border-image-repeat: stretch; border-image-slice: 100%; border-image-source: none; border-image-width: 1; border-left-color: rgb(0, 0, 0); border-left-style: none; border-left-width: 0px; border-right-color: rgb(0, 0, 0); border-right-style: none; border-right-width: 0px; border-top-color: rgb(0, 0, 0); border-top-left-radius: 0px; border-top-right-radius: 0px; border-top-style: none; border-top-width: 0px; bottom: auto; box-shadow: none; box-sizing: content-box; break-after: auto; break-before: auto; break-inside: auto; caption-side: top; clear: none; clip: auto; color: rgb(0, 0, 0); content: normal; cursor: auto; direction: ltr; display: block; empty-cells: show; float: none; font-family: Times; font-kerning: auto; font-optical-sizing: auto; font-size: 16px; font-stretch: 100%; font-style: normal; font-variant: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: normal; font-variant-east-asian: normal; font-weight: 400; height: 900px; image-orientation: from-image; image-rendering: auto; isolation: auto; justify-items: normal; justify-self: auto; left: auto; letter-spacing: normal; line-height: normal; list-style-image: none; list-style-position: outside; list-style-type: disc; margin-bottom: 8px; margin-left: 8px; margin-right: 8px; margin-top: 8px; max-height: none; max-width: none; min-height: 0px; min-width: 0px; mix-blend-mode: normal; object-fit: fill; object-position: 50% 50%; offset-distance: 0px; offset-path: none; offset-rotate: auto 0deg; opacity: 1; orphans: 2; outline-color: rgb(0, 0, 0); outline-offset: 0px; outline-style: none; outline-width: 0px; overflow-anchor: auto; overflow-wrap: normal; overflow-x: visible; overflow-y: visible; padding-bottom: 0px; padding-left: 0px; padding-right: 0px; padding-top: 0px; pointer-events: auto; position: static; resize: none; right: auto; scroll-behavior: auto; speak: normal; table-layout: auto; tab-size: 8; text-align: start; text-align-last: auto; text-decoration: none solid rgb(0, 0, 0); text-decoration-line: none; text-decoration-style: solid; text-decoration-color: rgb(0, 0, 0); text-decoration-skip-ink: auto; text-underline-position: auto; text-indent: 0px; text-rendering: auto; text-shadow: none; text-size-adjust: auto; text-overflow: clip; text-transform: none; top: auto; touch-action: auto; transition-delay: 0s; transition-duration: 0s; transition-property: all; transition-timing-function: ease; unicode-bidi: normal; vertical-align: baseline; visibility: visible; white-space: normal; widows: 2; width: 995px; will-change: auto; word-break: normal; word-spacing: 0px; z-index: auto; zoom: 1; -webkit-appearance: none; backface-visibility: visible; -webkit-border-horizontal-spacing: 0px; -webkit-border-image: none; -webkit-border-vertical-spacing: 0px; -webkit-box-align: stretch; -webkit-box-decoration-break: slice; -webkit-box-direction: normal; -webkit-box-flex: 0; -webkit-box-ordinal-group: 1; -webkit-box-orient: horizontal; -webkit-box-pack: start; -webkit-box-reflect: none; column-count: auto; column-gap: normal; column-rule-color: rgb(0, 0, 0); column-rule-style: none; column-rule-width: 0px; column-span: none; column-width: auto; backdrop-filter: none; align-content: normal; align-items: normal; align-self: auto; flex-basis: auto; flex-grow: 0; flex-shrink: 1; flex-direction: row; flex-wrap: nowrap; justify-content: normal; -webkit-font-smoothing: auto; grid-auto-columns: auto; grid-auto-flow: row; grid-auto-rows: auto; grid-column-end: auto; grid-column-start: auto; grid-template-areas: none; grid-template-columns: none; grid-template-rows: none; grid-row-end: auto; grid-row-start: auto; row-gap: normal; -webkit-highlight: none; hyphens: manual; -webkit-hyphenate-character: auto; -webkit-line-break: auto; -webkit-line-clamp: none; -webkit-locale: auto; -webkit-mask-box-image: none; -webkit-mask-box-image-outset: 0; -webkit-mask-box-image-repeat: stretch; -webkit-mask-box-image-slice: 0 fill; -webkit-mask-box-image-source: none; -webkit-mask-box-image-width: auto; -webkit-mask-clip: border-box; -webkit-mask-composite: source-over; -webkit-mask-image: none; -webkit-mask-origin: border-box; -webkit-mask-position: 0% 0%; -webkit-mask-repeat: repeat; -webkit-mask-size: auto; order: 0; perspective: none; perspective-origin: 497.5px 450px; -webkit-print-color-adjust: economy; -webkit-rtl-ordering: logical; shape-outside: none; shape-image-threshold: 0; shape-margin: 0px; -webkit-tap-highlight-color: rgba(0, 0, 0, 0.18); -webkit-text-combine: none; -webkit-text-decorations-in-effect: none; -webkit-text-emphasis-color: rgb(0, 0, 0); -webkit-text-emphasis-position: over right; -webkit-text-emphasis-style: none; -webkit-text-fill-color: rgb(0, 0, 0); -webkit-text-orientation: vertical-right; -webkit-text-security: none; -webkit-text-stroke-color: rgb(0, 0, 0); -webkit-text-stroke-width: 0px; transform: none; transform-origin: 497.5px 450px; transform-style: flat; -webkit-user-drag: auto; -webkit-user-modify: read-only; user-select: auto; -webkit-writing-mode: horizontal-tb; -webkit-app-region: none; buffered-rendering: auto; clip-path: none; clip-rule: nonzero; mask: none; filter: none; flood-color: rgb(0, 0, 0); flood-opacity: 1; lighting-color: rgb(255, 255, 255); stop-color: rgb(0, 0, 0); stop-opacity: 1; color-interpolation: srgb; color-interpolation-filters: linearrgb; color-rendering: auto; fill: rgb(0, 0, 0); fill-opacity: 1; fill-rule: nonzero; marker-end: none; marker-mid: none; marker-start: none; mask-type: luminance; shape-rendering: auto; stroke: none; stroke-dasharray: none; stroke-dashoffset: 0px; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 4; stroke-opacity: 1; stroke-width: 1px; alignment-baseline: auto; baseline-shift: 0px; dominant-baseline: auto; text-anchor: start; writing-mode: horizontal-tb; vector-effect: none; paint-order: normal; d: none; cx: 0px; cy: 0px; x: 0px; y: 0px; r: 0px; rx: auto; ry: auto; caret-color: rgb(0, 0, 0); line-break: auto;",
    cursor: "auto",
    cx: "0px",
    cy: "0px",
    d: "none",
    direction: "ltr",
    display: "block",
    dominantBaseline: "auto",
    emptyCells: "show",
    fill: "rgb(0, 0, 0)",
    fillOpacity: "1",
    fillRule: "nonzero",
    filter: "none",
    flex: "0 1 auto",
    flexBasis: "auto",
    flexDirection: "row",
    flexFlow: "row nowrap",
    flexGrow: "0",
    flexShrink: "1",
    flexWrap: "nowrap",
    float: "none",
    floodColor: "rgb(0, 0, 0)",
    floodOpacity: "1",
    font: "16px Times",
    fontDisplay: "",
    fontFamily: "Times",
    fontFeatureSettings: "normal",
    fontKerning: "auto",
    fontOpticalSizing: "auto",
    fontSize: "16px",
    fontStretch: "100%",
    fontStyle: "normal",
    fontVariant: "normal",
    fontVariantCaps: "normal",
    fontVariantEastAsian: "normal",
    fontVariantLigatures: "normal",
    fontVariantNumeric: "normal",
    fontVariationSettings: "normal",
    fontWeight: "400",
    gap: "normal",
    grid: "none / none / none / row / auto / auto",
    gridArea: "auto / auto / auto / auto",
    gridAutoColumns: "auto",
    gridAutoFlow: "row",
    gridAutoRows: "auto",
    gridColumn: "auto / auto",
    gridColumnEnd: "auto",
    gridColumnGap: "normal",
    gridColumnStart: "auto",
    gridGap: "normal normal",
    gridRow: "auto / auto",
    gridRowEnd: "auto",
    gridRowGap: "normal",
    gridRowStart: "auto",
    gridTemplate: "none / none / none",
    gridTemplateAreas: "none",
    gridTemplateColumns: "none",
    gridTemplateRows: "none",
    height: "900px",
    hyphens: "manual",
    imageOrientation: "from-image",
    imageRendering: "auto",
    inlineSize: "995px",
    isolation: "auto",
    justifyContent: "normal",
    justifyItems: "normal",
    justifySelf: "auto",
    left: "auto",
    length: 280,
    letterSpacing: "normal",
    lightingColor: "rgb(255, 255, 255)",
    lineBreak: "auto",
    lineHeight: "normal",
    listStyle: "outside none disc",
    listStyleImage: "none",
    listStylePosition: "outside",
    listStyleType: "disc",
    margin: "8px",
    marginBlockEnd: "8px",
    marginBlockStart: "8px",
    marginBottom: "8px",
    marginInlineEnd: "8px",
    marginInlineStart: "8px",
    marginLeft: "8px",
    marginRight: "8px",
    marginTop: "8px",
    marker: "none",
    markerEnd: "none",
    markerMid: "none",
    markerStart: "none",
    mask: "none",
    maskType: "luminance",
    maxBlockSize: "none",
    maxHeight: "none",
    maxInlineSize: "none",
    maxWidth: "none",
    maxZoom: "",
    minBlockSize: "0px",
    minHeight: "0px",
    minInlineSize: "0px",
    minWidth: "0px",
    minZoom: "",
    mixBlendMode: "normal",
    objectFit: "fill",
    objectPosition: "50% 50%",
    offset: "none 0px auto 0deg",
    offsetDistance: "0px",
    offsetPath: "none",
    offsetRotate: "auto 0deg",
    opacity: "1",
    order: "0",
    orientation: "",
    orphans: "2",
    outline: "rgb(0, 0, 0) none 0px",
    outlineColor: "rgb(0, 0, 0)",
    outlineOffset: "0px",
    outlineStyle: "none",
    outlineWidth: "0px",
    overflow: "visible",
    overflowAnchor: "auto",
    overflowWrap: "normal",
    overflowX: "visible",
    overflowY: "visible",
    overscrollBehavior: "auto",
    overscrollBehaviorBlock: "auto",
    overscrollBehaviorInline: "auto",
    overscrollBehaviorX: "auto",
    overscrollBehaviorY: "auto",
    padding: "0px",
    paddingBlockEnd: "0px",
    paddingBlockStart: "0px",
    paddingBottom: "0px",
    paddingInlineEnd: "0px",
    paddingInlineStart: "0px",
    paddingLeft: "0px",
    paddingRight: "0px",
    paddingTop: "0px",
    pageBreakAfter: "auto",
    pageBreakBefore: "auto",
    pageBreakInside: "auto",
    paintOrder: "normal",
    parentRule: null,
    perspective: "none",
    perspectiveOrigin: "497.5px 450px",
    placeContent: "normal",
    placeItems: "normal",
    placeSelf: "auto",
    pointerEvents: "auto",
    position: "static",
    quotes: "",
    r: "0px",
    resize: "none",
    right: "auto",
    rowGap: "normal",
    rx: "auto",
    ry: "auto",
    scrollBehavior: "auto",
    scrollMargin: "0px",
    scrollMarginBlock: "0px",
    scrollMarginBlockEnd: "0px",
    scrollMarginBlockStart: "0px",
    scrollMarginBottom: "0px",
    scrollMarginInline: "0px",
    scrollMarginInlineEnd: "0px",
    scrollMarginInlineStart: "0px",
    scrollMarginLeft: "0px",
    scrollMarginRight: "0px",
    scrollMarginTop: "0px",
    scrollPadding: "auto",
    scrollPaddingBlock: "auto",
    scrollPaddingBlockEnd: "auto",
    scrollPaddingBlockStart: "auto",
    scrollPaddingBottom: "auto",
    scrollPaddingInline: "auto",
    scrollPaddingInlineEnd: "auto",
    scrollPaddingInlineStart: "auto",
    scrollPaddingLeft: "auto",
    scrollPaddingRight: "auto",
    scrollPaddingTop: "auto",
    scrollSnapAlign: "none",
    scrollSnapStop: "normal",
    scrollSnapType: "none",
    shapeImageThreshold: "0",
    shapeMargin: "0px",
    shapeOutside: "none",
    shapeRendering: "auto",
    size: "",
    speak: "normal",
    src: "",
    stopColor: "rgb(0, 0, 0)",
    stopOpacity: "1",
    stroke: "none",
    strokeDasharray: "none",
    strokeDashoffset: "0px",
    strokeLinecap: "butt",
    strokeLinejoin: "miter",
    strokeMiterlimit: "4",
    strokeOpacity: "1",
    strokeWidth: "1px",
    tabSize: "8",
    tableLayout: "auto",
    textAlign: "start",
    textAlignLast: "auto",
    textAnchor: "start",
    textCombineUpright: "none",
    textDecoration: "none solid rgb(0, 0, 0)",
    textDecorationColor: "rgb(0, 0, 0)",
    textDecorationLine: "none",
    textDecorationSkipInk: "auto",
    textDecorationStyle: "solid",
    textIndent: "0px",
    textOrientation: "mixed",
    textOverflow: "clip",
    textRendering: "auto",
    textShadow: "none",
    textSizeAdjust: "auto",
    textTransform: "none",
    textUnderlinePosition: "auto",
    top: "auto",
    touchAction: "auto",
    transform: "none",
    transformBox: "view-box",
    transformOrigin: "497.5px 450px",
    transformStyle: "flat",
    transition: "all 0s ease 0s",
    transitionDelay: "0s",
    transitionDuration: "0s",
    transitionProperty: "all",
    transitionTimingFunction: "ease",
    unicodeBidi: "normal",
    unicodeRange: "",
    userSelect: "auto",
    userZoom: "",
    vectorEffect: "none",
    verticalAlign: "baseline",
    visibility: "visible",
    webkitAlignContent: "normal",
    webkitAlignItems: "normal",
    webkitAlignSelf: "auto",
    webkitAnimation: "none 0s ease 0s 1 normal none running",
    webkitAnimationDelay: "0s",
    webkitAnimationDirection: "normal",
    webkitAnimationDuration: "0s",
    webkitAnimationFillMode: "none",
    webkitAnimationIterationCount: "1",
    webkitAnimationName: "none",
    webkitAnimationPlayState: "running",
    webkitAnimationTimingFunction: "ease",
    webkitAppRegion: "none",
    webkitAppearance: "none",
    webkitBackfaceVisibility: "visible",
    webkitBackgroundClip: "border-box",
    webkitBackgroundOrigin: "padding-box",
    webkitBackgroundSize: "auto",
    webkitBorderAfter: "0px none rgb(0, 0, 0)",
    webkitBorderAfterColor: "rgb(0, 0, 0)",
    webkitBorderAfterStyle: "none",
    webkitBorderAfterWidth: "0px",
    webkitBorderBefore: "0px none rgb(0, 0, 0)",
    webkitBorderBeforeColor: "rgb(0, 0, 0)",
    webkitBorderBeforeStyle: "none",
    webkitBorderBeforeWidth: "0px",
    webkitBorderBottomLeftRadius: "0px",
    webkitBorderBottomRightRadius: "0px",
    webkitBorderEnd: "0px none rgb(0, 0, 0)",
    webkitBorderEndColor: "rgb(0, 0, 0)",
    webkitBorderEndStyle: "none",
    webkitBorderEndWidth: "0px",
    webkitBorderHorizontalSpacing: "0px",
    webkitBorderImage: "none",
    webkitBorderRadius: "0px",
    webkitBorderStart: "0px none rgb(0, 0, 0)",
    webkitBorderStartColor: "rgb(0, 0, 0)",
    webkitBorderStartStyle: "none",
    webkitBorderStartWidth: "0px",
    webkitBorderTopLeftRadius: "0px",
    webkitBorderTopRightRadius: "0px",
    webkitBorderVerticalSpacing: "0px",
    webkitBoxAlign: "stretch",
    webkitBoxDecorationBreak: "slice",
    webkitBoxDirection: "normal",
    webkitBoxFlex: "0",
    webkitBoxOrdinalGroup: "1",
    webkitBoxOrient: "horizontal",
    webkitBoxPack: "start",
    webkitBoxReflect: "none",
    webkitBoxShadow: "none",
    webkitBoxSizing: "content-box",
    webkitClipPath: "none",
    webkitColumnBreakAfter: "auto",
    webkitColumnBreakBefore: "auto",
    webkitColumnBreakInside: "auto",
    webkitColumnCount: "auto",
    webkitColumnGap: "normal",
    webkitColumnRule: "0px none rgb(0, 0, 0)",
    webkitColumnRuleColor: "rgb(0, 0, 0)",
    webkitColumnRuleStyle: "none",
    webkitColumnRuleWidth: "0px",
    webkitColumnSpan: "none",
    webkitColumnWidth: "auto",
    webkitColumns: "auto auto",
    webkitFilter: "none",
    webkitFlex: "0 1 auto",
    webkitFlexBasis: "auto",
    webkitFlexDirection: "row",
    webkitFlexFlow: "row nowrap",
    webkitFlexGrow: "0",
    webkitFlexShrink: "1",
    webkitFlexWrap: "nowrap",
    webkitFontFeatureSettings: "normal",
    webkitFontSizeDelta: "",
    webkitFontSmoothing: "auto",
    webkitHighlight: "none",
    webkitHyphenateCharacter: "auto",
    webkitJustifyContent: "normal",
    webkitLineBreak: "auto",
    webkitLineClamp: "none",
    webkitLocale: "auto",
    webkitLogicalHeight: "900px",
    webkitLogicalWidth: "995px",
    webkitMarginAfter: "8px",
    webkitMarginBefore: "8px",
    webkitMarginEnd: "8px",
    webkitMarginStart: "8px",
    webkitMask: "",
    webkitMaskBoxImage: "none",
    webkitMaskBoxImageOutset: "0",
    webkitMaskBoxImageRepeat: "stretch",
    webkitMaskBoxImageSlice: "0 fill",
    webkitMaskBoxImageSource: "none",
    webkitMaskBoxImageWidth: "auto",
    webkitMaskClip: "border-box",
    webkitMaskComposite: "source-over",
    webkitMaskImage: "none",
    webkitMaskOrigin: "border-box",
    webkitMaskPosition: "0% 0%",
    webkitMaskPositionX: "0%",
    webkitMaskPositionY: "0%",
    webkitMaskRepeat: "repeat",
    webkitMaskRepeatX: "",
    webkitMaskRepeatY: "",
    webkitMaskSize: "auto",
    webkitMaxLogicalHeight: "none",
    webkitMaxLogicalWidth: "none",
    webkitMinLogicalHeight: "0px",
    webkitMinLogicalWidth: "0px",
    webkitOpacity: "1",
    webkitOrder: "0",
    webkitPaddingAfter: "0px",
    webkitPaddingBefore: "0px",
    webkitPaddingEnd: "0px",
    webkitPaddingStart: "0px",
    webkitPerspective: "none",
    webkitPerspectiveOrigin: "497.5px 450px",
    webkitPerspectiveOriginX: "",
    webkitPerspectiveOriginY: "",
    webkitPrintColorAdjust: "economy",
    webkitRtlOrdering: "logical",
    webkitRubyPosition: "before",
    webkitShapeImageThreshold: "0",
    webkitShapeMargin: "0px",
    webkitShapeOutside: "none",
    webkitTapHighlightColor: "rgba(0, 0, 0, 0.18)",
    webkitTextCombine: "none",
    webkitTextDecorationsInEffect: "none",
    webkitTextEmphasis: "",
    webkitTextEmphasisColor: "rgb(0, 0, 0)",
    webkitTextEmphasisPosition: "over right",
    webkitTextEmphasisStyle: "none",
    webkitTextFillColor: "rgb(0, 0, 0)",
    webkitTextOrientation: "vertical-right",
    webkitTextSecurity: "none",
    webkitTextSizeAdjust: "auto",
    webkitTextStroke: "",
    webkitTextStrokeColor: "rgb(0, 0, 0)",
    webkitTextStrokeWidth: "0px",
    webkitTransform: "none",
    webkitTransformOrigin: "497.5px 450px",
    webkitTransformOriginX: "",
    webkitTransformOriginY: "",
    webkitTransformOriginZ: "",
    webkitTransformStyle: "flat",
    webkitTransition: "all 0s ease 0s",
    webkitTransitionDelay: "0s",
    webkitTransitionDuration: "0s",
    webkitTransitionProperty: "all",
    webkitTransitionTimingFunction: "ease",
    webkitUserDrag: "auto",
    webkitUserModify: "read-only",
    webkitUserSelect: "auto",
    webkitWritingMode: "horizontal-tb",
    whiteSpace: "normal",
    widows: "2",
    width: "995px",
    willChange: "auto",
    wordBreak: "normal",
    wordSpacing: "0px",
    wordWrap: "normal",
    writingMode: "horizontal-tb",
    x: "0px",
    y: "0px",
    zIndex: "auto",
    zoom: "1",
}